name: yankee_app
description: "Application mobile Yankee pour les clients"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.3.3
  get_it: ^8.2.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  intl: ^0.20.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  color: "#42a5f5"
  image: "assets/splash/splash_logo.png"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true